apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi-deploy
  labels:
    app: simpleapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi
    spec:
      containers:
        - name: apiserver
          image: melhiades/simpleapi:latest
          ports:
            - containerPort: 5000
        - name: client
          image: melhiades/alpine-curl:latest
          command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 10000']