apiVersion: v1
kind: Pod
metadata:
  name: limits-pod
spec:
  containers:
  - name: apiserver
    image: melhiades/simpleapi:latest
    ports:
      - containerPort: 5000
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
