apiVersion: v1
kind: Pod
metadata:
  name: apiserver-prod
  labels:
    env: production
    owner: rpozdeev
spec:
  containers:
  - name: apiserver
    image: melhiades/simpleapi:latest
    ports:
      - containerPort: 5000