apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
  - name: apiserver
    image: melhiades/simpleapi:latest
    ports:
      - containerPort: 5000
  - name: client
    image: melhiades/alpine-curl:latest
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 10000']