apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: apiserver
    image: melhiades/simpleapi:latest
    ports:
      - containerPort: 5000
    env:
      - name: TEST
        value: test_env