apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simpleapi-rs
  labels:
    app: simpleapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: apiserver
          image: melhiades/simpleapi:latest
          ports:
            - containerPort: 5000