apiVersion: v1
kind: Pod
metadata:
  name: ready
spec:
  containers:
  - name: apiserver
    image: melhiades/simpleapi:latest
    ports:
      - containerPort: 5000
    readinessProbe:
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 5000
