apiVersion: v1
kind: Pod
metadata:
  name: healthcheck
spec:
  containers:
  - name: apiserver
    image: melhiades/simpleapi:latest
    ports:
      - containerPort: 5000
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
        path: /health
        port: 5000
