apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: other
spec:
  containers:
  - name: client
    image: melhiades/alpine-curl:latest
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 10000']