apiVersion: v1
kind: Pod
metadata:
  name: apiserver
  labels:
    env: development
spec:
  containers:
  - name: apiserver
    image: melhiades/simpleapi:latest
    ports:
      - containerPort: 5000