apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
    - name: client
      image: melhiades/alpine-curl:latest
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 10000']
      env:
        - name: SECRET_API
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: apikey
